version: 2

models:
  - name: stg_customers
    description: "Cleaned version of raw customer data with consistent naming."
    columns:
      - name: customer_id
        description: "Unique identifier for the customer (renamed from 'id' in source)."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Customer's first name."
      - name: last_name
        description: "Customer's last name."

  - name: stg_orders
    description: "Cleaned orders with proper date casting and status validation."
    columns:
      - name: order_id
        description: "Unique order identifier."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to customer renamed from 'user_id' in source."
      - name: order_date
        description: "Date the order was placed casted to DATE type."
      - name: status
        description: "Current status of the order."
        tests:
          - accepted_values:
              arguments:
                values: ['placed', 'shipped', 'completed', 'returned', 'return_pending']

  - name: stg_payments
    description: "Payment records with amount converted from cents to dollars."
    columns:
      - name: payment_id
        description: "Unique payment identifier."
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to the order this payment belongs to."
      - name: payment_method
        description: "Method used for payment such as credit_card, gift_card."
      - name: amount
        description: "Payment amount in USD converted from cents in source."

  - name: dim_customers
    description: "Dimension table with customer information and order history metrics."
    columns:
      - name: customer_id
        description: "Unique customer identifier."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Customer's first name."
      - name: last_name
        description: "Customer's last name."
      - name: first_order_date
        description: "Date of the customer's first order."
      - name: most_recent_order_date
        description: "Date of the customer's most recent order."
      - name: number_of_orders
        description: "Total number of orders placed by the customer."

  - name: fct_orders
    description: "Fact table of completed orders with total payment amount."
    columns:
      - name: order_id
        description: "Unique order identifier."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to the customer who placed the order."
        tests:
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: order_date
        description: "Date the order was placed."
      - name: status
        description: "Order status (only 'completed' orders are included)."
      - name: total_amount
        description: "Total payment amount in USD for the order (sum of all payment methods)."